---
- name: Setting infrastructure for selenium testing with python
  vars:
    slave_machine: localhost
    gecko_driver_path: https://github.com/mozilla/geckodriver/releases/download/v0.24.0/geckodriver-v0.24.0-linux64.tar.gz
  hosts: "{{ slave_machine }}"
  tasks:

    - name: Install list of python packages using pip3
      pip: name={{item}}
      with_items:
        - selenium
      vars:
        pip_version: pip-3.3
      executable: "{{ pip_version }}"
      
    - name: Install list of packages
      package: name={{item}} state=present
      with_items:
          - firefox

    - name: Download and unarchive Selenium
      become: true
      become_user: root
      become_method: su
      unarchive:
        src: "{{ gecko_driver_path }}"
        dest: /usr/local/bin
        remote_src: yes
        mode: 0777

    - name: Change the geckodriver permissions
      file:
        path: /usr/local/bin/geckodriver
        # become: true
        # become_user: root
        # become_method: su
        owner: golan
        group: golan
        mode: 0777 

    #TODO add a var instead of the selenium path 
    - name: Ansible delete file
      file:
        path: /home/golan/Documents/geckodriver-v0.24.0-linux64.tar.gz
        state: absent

    #TODO add vars to values in this command
    - name: Copy file to server
      copy: 
        src: /home/golan/Documents/test.py 
        dest: /home/golan/Documents/test2.py
        owner: golan 
        group: golan 
        mode: 0777

    #TODO delete this folder after the playbook is done
    - name: See the current user  
      command: id
      become: yes
      become_user: golan
      become_method: su
      register: out
      ignore_errors: yes

    #TODO problem executing the script- possibly problem with perms
    - name: Execute script   
      command: python3 /home/golan/Documents/test2.py
      #register: out
      ignore_errors: yes

    - debug: var=out.stdout
    
    #TODO add variable to the file path
    - name: Delete the test file
      file:
        path: /home/golan/Documents/test2.py
        state: absent
    
    #TODO add variable to the file path
    - name: Delete the geckodriver file
      file:
        path: /usr/local/bin/geckodriver
        state: absent