---
- name: Setting infrastructure for selenium testing with python
  vars:
    slave_machine: localhost
    gecko_driver_path: https://github.com/mozilla/geckodriver/releases/download/v0.24.0/geckodriver-v0.24.0-linux64.tar.gz
    gecko_driver_version: geckodriver-v0.24.0-linux64.tar.gz
    test_src: /home/golan/Documents/test.py
    test_dest: /home/golan/Documents/test2.py
    test_owner: golan 
    test_group: golan 

  hosts: "{{ slave_machine }}"
  tasks:

    - name: Install list of python packages using pip3
      pip: name={{item}}
      with_items:
        - selenium
      vars:
        pip_version: pip-3.3
      executable: "{{ pip_version }}"
      
    - name: Install list of packages
      package: name={{item}} state=present
      with_items:
          - firefox

    - name: Download and unarchive Selenium
      become: true
      become_user: root
      become_method: su
      unarchive:
        src: "{{ gecko_driver_path }}"
        dest: /usr/local/bin
        remote_src: yes
        mode: 0777

    - name: Change the geckodriver permissions
      file:
        path: /usr/local/bin/geckodriver
        # become: true
        # become_user: root
        # become_method: su
        owner: golan
        group: golan
        mode: 0777 

    - name: Delete the driver tar file
      file:
        path: /home/golan/Documents/"{{ gecko_driver_version }}"
        state: absent

    - name: Copy test file to server
      copy: 
        src: "{{ test_src }}"
        dest: "{{ test_dest }}"
        owner: "{{ test_owner }}"
        group: "{{ test_group }}"
        mode: 0777

    - name: See the current user  
      command: id
      become: yes
      become_user: golan
      become_method: su
      register: out
      ignore_errors: yes

    #TODO problem executing the script- possibly problem with permissons
    - name: Execute script   
      command: python3 "{{ test_dest }}"
      #register: out
      ignore_errors: yes

    - debug: var=out.stdout
    
    - name: Delete the test file
      file:
        path: "{{ test_dest }}"
        state: absent
    
    - name: Delete the geckodriver file
      file:
        path: /usr/local/bin/geckodriver
        state: absent